### ISSUE TITLE
BOM is too vague

### ISSUE THREAD

**Issue by hlide** [tebl/C64-Pi1541-II#1]
Could it be possible to add references? Several entries are too vague to be sure not to order wrong components. I bought the plates but as such I cannot order the components. It is frustrating. I should really have examine the BOM thoroughly to make a decision to buy your plates or not.

**Comment by tebl** [comment]
Hello! I'm sorry you feel frustrated by them, that was not my intention. I can't add much in the way of links as the bigger chains such as mouser is effectively unavailable where I live, so I couldn't do any form of verification.

On the specifics, is there anything specific components you were wondering about? That way I can try and add more details to the BOM.

**Comment by hlide** [comment]
Hi,

they are mostly:

# Pi1541-II Module


Reference | Item | Count | Remarks
-- | -- | --|--
BZ1 | Buzzer (7mm pin spacing, 5mm OK) | (1) | Too much variety that I cannot trust which one
C1 | 100nF ceramic capacitor | 1 | Package?
IC1 * | SSD1306 OLED-display 128x64 (0.96") | (1) | Too much variety that I cannot trust which one. Size, I2C, SPI?
IC3 | 4ch I2C level converter module | 1 | Too much variety that I cannot trust which one. I'm clueless for this one as I have no picture.
J1 | 2.1mm x 5.5mm barrel plug | 1 |  I'm clueless for this one as I have no picture. Searches are unsuccessful.
J2, J3 | Female S-terminal 6pin DIN PCB | 1 (1) | Where to find them? Are their pinout specifically U-shape or V-shape?

Thanks.

Pictures may help to disambiguate. Package, Protocole, etc.

EDIT: There is indeed a picture showing the OLED-display: I2C.

**Comment by tebl** [comment]
Level converter: https://www.ebay.co.uk/itm/272249807035
Barrel connector: https://www.ebay.com/itm/223085851516
Oled: https://www.ebay.com/itm/352665854406
Din plug: https://www.ebay.com/itm/114190129105
Capacitor 5mm spacing 100nF: https://www.ebay.de/itm/283823656509
Buzzer: https://www.ebay.com/itm/143731106844

These I think should be correct, but you should probably find similar listing with better shipping (I just looked for something with pictures). I have also added some pictures of the components I have on hand to the gallery folder.

**Comment by hlide** [comment]
Thanks
