### ISSUE TITLE
Fork with modifications

### ISSUE THREAD

**Issue by Cologran** [tebl/C64-Pi1541-II#4]
Hello!

I made a fork of your projekt and some little modification. 

**Changes "Module":**
1)Power Connector moved from the left side to the back side
2) PCB cut like in "Faceplate" und "Backplate"
3) moved the speaker 1 mm down and left
4) reroute conducting paths around the speaker
5) reroute conducting paths for the power jack and the display
6) remove the soldering holes for the display (-> Faceplate)

**Changes "Faceplate":**
1) redesign the visable cupper
2) remove the mounting holes for the display

**Changes "FaceplateB":**
1) redesign the visable cupper
2) remove the mounting holes for the display

**Changes "Backplate":**
1) redesign the visable cupper

Perhaps you've time to take a look at it (https://github.com/Cologran/C64-Pi1541-II) and if you like I can make a pull request.

**Comment by tebl** [comment]
Thanks, it is fun to see my little project bring joy to more people than just me. I've adapted some of the changes into my design, moving the power connector and reinstating the cutouts on the main PCB were good ideas.
