### ISSUE TITLE
options.txt

### ISSUE THREAD

**Issue by danko79** [tebl/C64-Pi1541-II#6]
Hi, i have a problem with your project, do you share a options.txt fully configured?

**Comment by tebl** [comment]
I don't have one on hand just at this moment as I cannibalised my II when
building Pi1541-III. Made a video that goes through all of the steps for
setting up III, on yours you need ssd1306 as screen type and should skip
the part about rotary encoder.

https://youtu.be/a_sJkwbnSls?si=3NoxgRjHCaF-GWNv

lør. 16. mars 2024, 17:23 skrev danko79 ***@***.***>:

**Comment by danko79** [comment]
Got this error:
?DEVICE NOT PRESENT ERROR

**Comment by tebl** [comment]
Assuming you remembered to set splitIECLines = 1 and the display and so on
is functional, a likely fault is that the level converter is either broken
or the wrong type. In a lot of 10, you often get 2-3 that never quite work.

søn. 17. mars 2024, 20:53 skrev danko79 ***@***.***>:

**Comment by danko79** [comment]
Ok i bought this;
Just found this amazing item on AliExpress. Check it out! 
2,48€  66%OFF | 10pcs 4 channel IIC I2C Logic Level Converter Bi-Directional Module 5V to 3.3V
https://a.aliexpress.com/_EH0Qjyv

**Comment by tebl** [comment]
It does look like it is the right type.

søn. 17. mars 2024, 23:02 skrev danko79 ***@***.***>:

**Comment by danko79** [comment]
I try other 4 logic level, display off and same problem ?DEVICE NOT PRESENT ERROR
Attach my options file, take look.
[options.txt](https://github.com/tebl/C64-Pi1541-II/files/14638991/options.txt)

**Comment by danko79** [comment]
I found the problem, i have a 2 Raspberry Pi 3B+ and a one Raspberry Pi 3 A+ purchased recently, i don't know why they don't works, work fine with a RPI 3B+ purchased years ago, any suggestion?

**Comment by danko79** [comment]
Found solution! the new batch Raspberry Pi required a new firmware (bootcode.bin, fixup.dat and start.elf ) i use a old version take from https://cbm-pi1541.firebaseapp.com/ not working with new revision of the Raspberry.
Close this issue.
Thanks

**Comment by tebl** [comment]
That's excellent, glad you got it working! I wasn't aware that there had
been any changes, all of my Pi's are pretty ancient at this point - learn
something new every day 😀

tir. 19. mars 2024, 21:36 skrev danko79 ***@***.***>:

**Comment by danko79** [comment]
I love this project, but I would like to ask you a favor, two simple mods, in the module can you put buzzer with a 5mm pin spacing?
In the faceplate the characters (power , drive , select etc.) are too small, can you make them double bigger?
Thanks
